### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by bdyetton** [gonzaloflirt/link-python#1]
Hi, 
I'm getting some linker errors about missing <Python.h> dependencies when I try to install.
Can you please add all required dependencies to the README. thanks.

**Comment by gonzaloflirt** [comment]
@bdyetton What system are you on? I only tested on osx with a brew install of `python3`. If you're on Linux you might have to install some `python3-dev` packet or something like that.

**Comment by bdyetton** [comment]
Linux (Raspbian). Hmm ok, how Python 2.7 portable is this?
I have a feeling that file is related to the python c++ binding module, did you have to brew install that? What is that module exactly?

**Comment by bdyetton** [comment]
My bad, i didn't have dev for python3, only for python2. I'll close this issue once I get it successfully installed on my machine.

**Comment by gonzaloflirt** [comment]
The pybind11 readme says it's supposed to work with Python 2.7 and GCC 4.8 or newer. I think the wrapper should generally work with Python 2.7 but the example app will require some change.

**Comment by bdyetton** [comment]
Build successful after installing python3-dev and updating gcc to version 4.9. Thanks.
