### ISSUE TITLE
issue with Callbacks....

### ISSUE THREAD

**Issue by dzelionis** [gonzaloflirt/link-python#6]
there is issue with a callbacks, when you try to define one you get the following error:

def cb(value):
  pass
l.setStartStopCallback(cb)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: setStartStopCallback(): incompatible function arguments. The following argument types are supported:
    1. (self: link.Link, arg0: std::function<void (bool)>) -> None

Invoked with: <link.Link object at 0x7fa6c535efb0>, <function a at 0x7fa6c5324670>

I have modified  src/Link.cpp, at very top added :
#include <pybind11/functional.h>

After recompiling callbacks is wortking now fine.

**Comment by gonzaloflirt** [comment]
@dzelionis Thanks a lot!
I pushed a fix dfba469387a638f1ce21c6a85af1081a679052b3.

**Comment by dzelionis** [comment]
@gonzaloflirt. thats no problem at all...and thanks for pushing  a fix!
