### ISSUE TITLE
cant change bpm

### ISSUE THREAD

**Issue by MatthiasSchmid93** [gonzaloflirt/link-python#7]
hello folks,

cant figure out how you can change the bpm when joined in link session. 
i tryed several methods looking at the example code and the ableton link source code, but nothing worked.

since you have coded this, can you give me a example line where you change the bpm to a specific value.

thank you :)

**Comment by gonzaloflirt** [comment]
This changes the tempo to 234 bpm:
```
s = l.captureSessionState()
s.setTempo(234, l.clock().micros())
l.commitSessionState(s)
```

**Comment by MatthiasSchmid93** [comment]
runs flawlessly, keep up the good work!

thanks!
